### ISSUE TITLE
Use gerber layout in online gerber viewer

### ISSUE THREAD

**Issue by NilsMinor** [uwcms/ZYNQ-IPMC-HW#18]
Hey UW Madison CMS Group,

My name is Nils, my company is building an online gerber viewer and we are looking for some good looking example projects. We would like to add the ZYNQ IMPC gerber files as an example project into our viewer. As it is released under MIT License it should not be a problem but I wanted to ask anyway.

The viewer will be available under stackrate.de/viewer (anytime soon)

Thanks,
Nils

**Comment by jtikalsky** [comment]
Sure, no problem.
